#!/bin/bash

WORKING_INSTALLATION_PATH="`dirname \"$0\"`"
WORKING_INSTALLATION_PATH="`( cd \"$WORKING_INSTALLATION_PATH\" && pwd )`"
. $WORKING_INSTALLATION_PATH/CONFIGURATION

clear
echo " "
echo "-> INSTALLER STEP 2 INITIATED : SYSTEM UPDATE"
echo " "
sleep 3

# UPDATE THE SYSTEM
dnf -y update

$WORKING_INSTALLATION_PATH/step3.sh

# END OF SCRIPT - STEP 2

