#!/bin/bash

WORKING_INSTALLATION_PATH="`dirname \"$0\"`"
WORKING_INSTALLATION_PATH="`( cd \"$WORKING_INSTALLATION_PATH\" && pwd )`"
. $WORKING_INSTALLATION_PATH/CONFIGURATION

clear
echo "*** PLEASE WAIT - INSTALLATION IN PROGRESS . . ."
echo " "
sleep $INSTALLER_SLEEP_ON_BOOT
echo "*** INSTALLER STEP 2 INITIATED"
echo " "


# UPDATE THE SYSTEM
dnf -y update


# PREPARING NEXT BOOT
sed -i '/step2.sh/d' /etc/rc.local

cat >>/etc/rc.local <<EOL
$WORKING_INSTALLATION_PATH/step3.sh
EOL


# REMOVE ENVIRONMENT CONFIGURATION
. $WORKING_INSTALLATION_PATH/REMOVE_CONFIGURATION

reboot

# END OF SCRIPT

